config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :data_objects do |data_object|
    data_object.resources :data_entries
  end

  map.resources :data_types do |data_type|
    data_type.resources :data_fields
  end

  map.resources :data_types, :shallow => true do |data_type|
    data_type.resources :data_objects
  end

  map.resources :stats, :collection => {:destroy_all => :delete}, 
                        :member => {:location_more => :get}

  map.resources :food_items

  map.taskr4rails "taskr4rails", :controller => 'taskr4rails', :action => 'execute'

  map.root :controller => "index"

  map.connect ':controller/service.wsdl', :action => 'wsdl'
  map.connect 'payform/interface/:action',
    :controller => "/payform/interface"
  map.connect 'support/:dept/:loc/plain', :controller => 'support', :action => 'index', :plain => true
  map.connect 'support/:dept/:loc'  , :controller => 'support', :action => 'index'

  map.connect ':controller/:action/:id'
end

app/models/announcement.rb
class Announcement < Notice
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :location_groups
  belongs_to :department
  belongs_to :for_department,
              :class_name => "Department",
              :foreign_key => "for_department_id"
  
  validate :department_or_locations_and_groups
  validates_presence_of :content
  
  named_scope :not_yet_ended, lambda{ {:conditions => ["end_time > ? OR end_time is NULL", Time.now]} }
  
  def validate
    errors.add("Time between start and expiration") if end_time and start_time >= end_time
  end
  
  def department_or_locations_and_groups
    if locations.empty? and location_groups.empty?
      errors.add(:department_id, " or location(s) and/or location group(s) must be specified") if department.nil?
    end
  end
  
  def self.active(department)
    r = []
    for announcement in find :all, :conditions => ["start_time <= ? and department_id = ?", Time.now, department.id]
      r << announcement if !announcement.end_time or announcement.end_time >= Time.now
    end
    r
  end
  
  def self.upcoming(department)
    find :all, :conditions => ["start_time > ? and department_id = ?", Time.now, department.id]
  end
  
  
  def authorized?(object)
    result = case object
      when LocationGroup: "for location group #{object.short_name}" if location_groups.include? object
      when Location: "for location #{object.short_name}" if locations.include? object
      #when User: "for user #{object.name}" if users.include? object.id
      #comment: i think all the users should be displayed, otherwise a user might trash a sticky that was supposed to be addressed to more than one person -snl
      when User: "for users #{self.user_names}" if users.include? object
      when Department: "for department #{object.name}" if for_department == object
    end
    #self.auth_text = result
    self.auth_text = self.auth_full_list if result
  end
  
end

app/controllers/shift_admin/announcements_controller.rb
class ShiftAdmin::AnnouncementsController < ShiftAdminController
  
  def index
    redirect_with_flash flash[:notice], :action => :manage, :id => get_dept_from_url.id
  end
  
  def manage
    @department = get_dept_from_url
    if !params[:id] or params[:id].to_i != @department.id
      redirect_to :action => :manage, :id => @department.id and return
    end
    @announcement = Announcement.new
  end
  
  def add
    if params[:announcement] and request.post?
      @announcement = Announcement.new(params[:announcement])
      @announcement.department = get_dept_from_url
      @announcement.author = @user
      @announcement.start_time = Time.now if params[:start_time_choice] == 'now'
      @announcement.end_time = nil if params[:end_time_choice] == 'indefinite'
      if @announcement.save
        flash = "Announcement Saved"
      else
        flash = "Error saving"
      end
      redirect_with_flash flash, :action => :manage, :id => @announcement.department and return 
    end
  end
  
  def edit
    @announcement = Announcement.find_by_id(params[:id])
    if @announcement 
      @department = @announcement.department
      if params[:announcement] and request.post?   
        @announcement.for_department = nil
        @announcement.location_groups = []
        @announcement.locations = []
        params[:announcement][:start_time] = Time.now if params[:start_time_choice] == 'now'
        params[:announcement][:end_time] = nil if params[:end_time_choice] == 'indefinite'
        if @announcement.update_attributes(params[:announcement])
          redirect_with_flash "Announcement Saved", :action => :manage, :id => @announcement.department and return 
        end
      end
    else
      redirect_with_flash "Invalid Announement", :action => :manage, :id => session["current_chooser_choice"][self.controller_name] and return
    end
  end
  
  def update_checkboxes
    @department = Department.find(session["current_chooser_choice"][self.controller_name])
    @announcement = Announcement.new(params[:announcement])
    render :update do |page|
      page.replace_html('checkboxes_div', :partial => "checkboxes")
    end
  end
  
  def delete
    announcement = Announcement.find_by_id params[:id]
    if announcement && request.post?
      if announcement.destroy
        redirect_with_flash "announcement Deleted", :action => :index
      end
    else
    redirect_with_flash "Invalid announcement", :action => :index
    end
  end
  
  def controller_name
    ShiftAdminController.controller_name
  end
  
  protected
  

  
end

app/controllers/shift_admin/calendar_controller.rb
require 'icalendar'
require 'date'

class ShiftAdmin::CalendarController < ShiftAdminController

  include Icalendar

  def controller_name
    ShiftAdminController.controller_name
  end

  def index
    @user = get_user
    @department = get_department
    @location_groups = @department.location_groups.select { |lg| lg.allow_view? @user }
    @locations = @location_groups.map { |group| group.locations }.flatten!

    if request.post?
      @start_date = params[:start_date_select]
      @end_date = params[:end_date_select]
      @shifts = Shift.all_between(@start_date, @end_date).filter_by_department(@department)
      cal = Calendar.new
      @shifts.each do |shift|
        cal.event do
          dtstart     shift.start.to_datetime
          dtend       shift.end.to_datetime
          summary     "#{shift.user.name} @ #{shift.location.long_name}"
        end
      end

      cal_string = cal.to_ical
      filename = Time.now.strftime("calendar_%Y%m%d%H%M%S.ics")
      File.open(filename, 'w') {|f| f.write(cal_string) }
      send_file(filename)
  
    end
    
  end

end

app/controllers/shift_admin/restrictions_controller.rb
class ShiftAdmin::RestrictionsController < ShiftAdminController
  
  def index
    redirect_with_flash flash[:notice], :action => :manage, :id => @department.id
  end
  
  def manage
    @department = get_dept_from_url
    # if !params[:id] or params[:id].to_i != @department.id
    #   redirect_to(:action => :manage) and return
    # end
    if params[:restriction] && request.post?
      @restriction = Restriction.new(params[:restriction])
      @restriction.department = @department
      @restriction.max_subs = nil unless @restriction.max_subs > 0
      @restriction.starts = Time.now if params[:starts_choice] == 'now'
      @restriction.expires = nil if params[:expires_choice] == 'indefinite'
      @restriction.hours_limit += params[:minutes][:limit].to_i / 60.0
      @restriction.hours_limit = nil unless @restriction.hours_limit > 0
      if @restriction.save
        flash[:notice] = "Restriction Saved"
      end
    else
      @restriction = Restriction.new(:department_id => @department.id)
    end
  end
  
  def edit
    @restriction = Restriction.find_by_id(params[:id])
    if @restriction
      if params[:restriction] && request.post?
        @restriction.for_department = nil
        @restriction.location_groups = []
        @restriction.locations = []
        params[:restriction][:max_subs] = nil unless params[:restriction][:max_subs].to_i > 0
        params[:restriction][:starts] = Time.now if params[:starts_choice] == 'now'
        params[:restriction][:expires] = nil if params[:expires_choice] == 'indefinite'
        params[:restriction][:hours_limit] = params[:restriction][:hours_limit].to_i + params[:minutes][:limit].to_i / 60.0
        params[:restriction][:hours_limit] = nil unless params[:restriction][:hours_limit] > 0
        if @restriction.update_attributes(params[:restriction])
          redirect_with_flash("Restriction Saved", :action => :manage) and return 
        end
      end
    else
      redirect_with_flash("Invalid Restriction", :action => :manage) and return
    end
  end
  
  def update_checkboxes
    @department = Department.find(session["current_chooser_choice"][self.controller_name])
    @restriction = Restriction.new(params[:restriction])
    render :update do |page|
      page.replace_html('checkboxes_div', :partial => "checkboxes")
    end
  end
  
  def delete
    restriction = Restriction.find_by_id params[:id]
    if restriction && request.post?
      if restriction.destroy
        redirect_with_flash "Restriction Deleted", :action => :index
      end
    else
    redirect_with_flash "Invalid Restriction", :action => :index
    end
  end
  
  def controller_name
    ShiftAdminController.controller_name
  end
  
  protected
  

  
end

app/controllers/shift_admin/time_slots_controller.rb
class ShiftAdmin::TimeSlotsController < ShiftAdminController
  before_filter :fetch_schedule_view_variables
  def controller_name
    ShiftAdminController.controller_name
  end
  
  def index
    week_date = params[:date].blank? ? Date.today : Date.parse(params[:date])
    @week_days = get_week week_date
    
    @time_choices_select = get_department.shift_configuration.minute_blocks.map{|m| [m.min_to_am_pm, m]}

    @loc_groups_all = fetch_location_groups
    @loc_groups = pref_filter(@loc_groups_all)
    @locations = @loc_groups.collect(&:locations).flatten

    wdays = (params[:days] || []).map { |day| day.to_i }

    if request.post? and (params[:time_slots] || params[:new_slot])
      if params[:new_slot]
        start_time = params[:new_slot][:start_in_minute].to_i.minutes
        end_time = params[:new_slot][:end_in_minute].to_i.minutes
      end
      
      error_list = []
      (params[:location_ids] || []).each do |id|
        wdays.each do |day|
          #need @time_slot here to store error messages
          slot = TimeSlot.create(:location_id => id, :start => @week_days[day] + start_time , :end => @week_days[day] + end_time)
          error_list << slot.errors.full_messages
        end
      end

      (params[:time_slots] || {}).keys.each do |slot_id|
        slot = TimeSlot.find(slot_id) #need this because we need slot.date
        slot.update_attributes params[:time_slots][slot_id]
        slot.destroy if (params[:delete_ids]||[]).include?(slot_id) and slot.date >= Date.today
        error_list << slot.errors.full_messages

      end
      a = error_list.flatten.to_sentence
      flash[:notice] = a.blank? ? 'successfully updated.' : a
      redirect_to :action => 'index', :date => params[:date]
    end
  end
end

app/helpers/shift_admin/calendar_helper.rb
module ShiftAdmin::CalendarHelper
end

app/helpers/shift_admin/restrictions_helper.rb
module ShiftAdmin::RestrictionsHelper
end

app/helpers/shift_admin/time_slots_helper.rb
module ShiftAdmin::TimeSlotsHelper
  def label_slot(slot)
    slot.date < Date.today ? 'passed' : 'shift_time'
  end
  
  def th_with_description(ts)
    "<th title='%s'>%s</th>" % [ts.date.to_s(:long), ts.date.to_s(:day)]
  end
  
end

app/helpers/shift_admin_helper.rb
module ShiftAdminHelper
  def light_print_cell(type, from, to, object = nil, content = "")
    span = (to - from) / @dept_gran #DON'T HARD CODE GRANULARITY UGH! :P
    return '' if span==0
    content = object.user.name if object.class==ShiftTemplateItem
    "<td class='%s' colspan='%s'>%s</td>" % [type, span, content]
  end
  
  #use this instead of order_by because we want an array, not ordered hash
  def split_items_by_days(list)
    a = [[], [], [], [], [], [], []]
    list.each { |e| a[e.wday] << e }
    a
  end

  #here items can be shifts ot time_slots
  def split_to_days(week_items)
    wd = [ [], [], [], [], [], [], [] ]
    for item in week_items
      num = item.start.wday
      wd[num] << item
    end
    wd
  end
  
  def report_links_group_select
    link_group_select = []
    link_group_select.push([@department.name, "department" + @department.id.to_s]) if department_admin?
#    @link_group_select.push(["----------", nil])
    link_group_select = @link_group_select|(@location_groups.map{|lg|[lg.short_name, "lg" + lg.id.to_s]})
#    @link_group_select.push(["----------", nil])
    link_group_select = @link_group_select|(@locations.map{|loc|[loc.short_name, "loc" + loc.id.to_s]})
    return link_group_select
  end
  
end

app/views/shift_admin/announcements/_announcement.html.erb
<div class="restriction">    
<strong>Announcement:</strong><br /> <%= announcement.content%>  <br/>
<% time_format = '%A, %B %d, %Y at %I:%M%p' -%>
<strong>Starts:</strong> <%= announcement.start_time.strftime(time_format) %><br/>
<strong>Ends:</strong> <%= announcement.end_time ? announcement.end_time.strftime(time_format) : "indefinitely" %><br/>
<%= "<strong>Department:</strong> " + announcement.for_department.name + "<br/>" if announcement.for_department %>
<%= "<strong>Location Groups:</strong> " unless announcement.location_groups.empty?%>  
<% for loc_group in announcement.location_groups %>
  <%= loc_group.short_name %><%= loc_group == announcement.location_groups[-1] ? "<br/>" : ", " %>
<% end %>
<%= "<strong>Locations:</strong> " unless announcement.locations.empty?%>
<% for location in announcement.locations %>
  <%= location.short_name %><%= location == announcement.locations[-1] ? "<br/>" : ", " %>
<% end %>
<%= link_to '[delete]', { :action => 'delete', :id => announcement}, { :method  => :post } %>
<%= link_to '[edit]',   { :action => 'edit',   :id => announcement} %>  
</div>

app/views/shift_admin/announcements/_announcement_form.html.erb
<% form_for(:announcement, @announcement, :url => {:controller => "/shift_admin/announcements", :action => (controller.action_name == "manage" ? "add" : "edit"), :id => @department.id}, :html => {:id => 'announcement_form', :multipart => :true}) do  |form|%> 
    Announcement:
    <%= form.text_field :content %>
    <br />
    From:<br/>
    <%= radio_button_tag 'start_time_choice', 'date', :checked => true -%>
      <%= datetime_select 'announcement', 'start_time' %><br />
    <%= radio_button_tag 'start_time_choice', 'now' -%> Now<br />
    Until:<br/>
    <%= radio_button_tag 'end_time_choice', 'date', :checked => true -%>
      <%= datetime_select 'announcement', 'end_time' %><br />
    <%= radio_button_tag 'end_time_choice', 'indefinite' -%> Indefinitely<br />
    Applies to:<br/>
    <div id="checkboxes_div"><%= render :partial => 'checkboxes'%></div>
    <%= submit_tag "Save" %>
  <% end %>
<%= observe_form 'announcement_form', :url => { :action => 'update_checkboxes', :id => @department.id }, :frequency => 0.5 %>

app/views/shift_admin/announcements/_checkboxes.html.erb
  <%= check_box_tag "announcement[for_department_id]", @department.id, @announcement.for_department, :disabled => false %><%= @department.name %> (department-wide)<br />
  <% for location_group in @location_groups do %>
    &nbsp;&nbsp;&nbsp;
    <%= check_box_tag "announcement[location_group_ids][]", location_group.id, (@announcement.location_groups.include?(location_group) or @announcement.for_department), :disabled => @announcement.for_department %><%= location_group.long_name %><br />
    <% for location in location_group.locations do %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= check_box_tag "announcement[location_ids][]", location.id, (@announcement.locations.include?(location) or (@announcement.location_groups.include?(location_group) or @announcement.for_department)), :disabled => (@announcement.location_groups.include?(location_group) or @announcement.for_department) %><%= location.long_name %><br />
    <% end %>
  <% end %>

app/views/shift_admin/announcements/edit.html.erb
<div class="shift_form">
<%= error_messages_for :announcement %>
<fieldset>
  <legend>Edit announcement</legend>
  <%= render :partial => "announcement_form" %>
</fieldset>
</div>

app/views/shift_admin/announcements/manage.html.erb
<% title "Manage announcements" %>
<div class="shift_form">
<%= error_messages_for :announcement %>
<fieldset>
  <legend>Current announcements</legend>
    <p><strong>Active:</strong><br/>
      <%= render :partial => "announcement", :collection => Announcement.active(@department) %>
    </p>
    <p><strong>Upcoming:</strong><br/>
      <%= render :partial => "announcement", :collection => Announcement.upcoming(@department) %>
    </p>
</fieldset>
<br />
<fieldset>
  <legend>Add announcement</legend>
    <%= render :partial => "announcement_form" %>
</fieldset>
</div>